### ISSUE TITLE
dataset release

### ISSUE THREAD

**Issue by amiltonwong** [gy20073/BDD_Driving_Model#1]
Hi, @gy20073 ,

When will the BDD-V dataset be released?

**Comment by xuhuazhe** [comment]
It will be released very soon. Thank you!

**Comment by kelvin820** [comment]
Hi @gy20073 ,

How large is the dataset? 100GB?or 500GB?

**Comment by gy20073** [comment]
The initial batch we are releasing will be around 550G.

**Comment by huanhuanxuxu** [comment]
hi could I ask when would the dataset be released or some time tables available? Thank you!

**Comment by gy20073** [comment]
For dataset access issues, please send email to Fisher Yu <i@yf.io>

**Comment by xuhuazhe** [comment]
BDD 100K is released. Close the issue.
