### ISSUE TITLE
A question about wrapper_test.ipynb

### ISSUE THREAD

**Issue by ilovepopcorn** [gy20073/BDD_Driving_Model#11]
The part of visualization is not completed( I saw 'TODO Improved visualization' in step 'Run a pretrained Model'), right?  I try to run wrapper_test.ipynb by Jupyter notebook, the first, the second cell and the first three lines of the third cell are okay, and I can see an image. How can I see some cool results just like photos in your paper? 
Sorry to bother and thanks.

**Comment by gy20073** [comment]
Hi, there is a visualization function in the wrapper.py file: 
https://github.com/gy20073/BDD_Driving_Model/blob/master/wrapper.py#L143
