### ISSUE TITLE
Unable to understand the output of the continuous datadriven pretrained model

### ISSUE THREAD

**Issue by thanif** [gy20073/BDD_Driving_Model#2]
I have used the datadriven pretrained model to test it using wrapper_test on an image and the function "observe_a_frame" gives an output of 362 values and I am unable to understand what these values are and what they represent.

**Comment by gy20073** [comment]
The 362 values are the predicted distribution for future yaw rate and speed. To be specific, the first half (181 values) are the predicted yaw rate distribution, and second half is for speed. We used a binning approach to represent the distribution, by discretizing the support set for yaw rates (-pi/2 rad/second to pi/2 rad/second) into 181 bins. So those 181 values are the probability mass that is predicted for those bins. 

Those being said, you could further look at some utility functions in wrapper.py to get the distribution's MAP(continuous_MAP), or get probability density at the yaw rate you wanna query(continuous_muti_querys_pdf), or generate a visualization of the distribution (generate_visualization).

**Comment by thanif** [comment]
Thank You very much

**Comment by Shaswat27** [comment]
@gy20073 What's the discretization for the speeds?

**Comment by neel04** [comment]
hey @gy20073 really sorry to ping you, just had a very quick query - when building the `TFRecords`, inspecting the speed I get alternating numbers like this:

What do these alternating numbers mean? 🤔 
```
[10.70574,
 0.5527634,
 10.70574,
 0.5527634,
 10.70574,
 0.5527634,
 10.70574,
 0.5527634,
 10.70574,
 0.5527634,
 10.70574,
 0.5527634,
 10.710104,
 0.55298877,
 10.716429,
 0.5533153,
 10.7227545,
 0.5536419,
 10.729079,
 0.5539684,
 10.735403,
 0.554295,
 10.741728,
 0.5546216,
 10.748054,
 0.5549482,
 10.754378,
 0.5552747,
 10.760703,
 0.5556013,
 10.767028,
 0.5559279,
 10.773353,
 0.55625445,
 10.779677,
 0.556581,
 10.786003,
 0.5569076,
 10.792327,
 0.55723417,
 10.798653,
 0.5575607,
 10.804977,
 0.5578873,
 10.811302,
 0.55821383,
 10.817627,
 0.5585404,
 10.823952,
 0.558867,
 10.8302765,
 0.5591936,
 10.836601,
 0.5595201,
 10.842926,
 0.5598467,
 10.849251,
 0.5601733,
 10.8555765,
 0.56049985,
 10.8619,
 0.5608264,
 10.868225,
 0.561153,
 10.874551,
 0.56147957,
 10.880875,
 0.5618061,
 10.8872,
 0.5621327,
 10.893525,
 0.5624593,
 10.89985,
 0.5627858,
 10.906175,
 0.56311244,
 10.9125,
 0.563439,
 10.918824,
 0.5637655,
 10.925149,
 0.5640921,
 10.931475,
 0.5644187,
 10.937799,
 0.56474525,
 10.944124,
 0.5650718,
 10.950449,
 0.5653984,
 10.956774,
 0.56572497,
 10.9630995,
 0.56605154,
 10.969424,
 0.5663781,
 10.97575,
 0.5667047,
 10.982074,
 0.56703126,
 10.9883995,
 0.56735784,
 10.994724,
 0.5676844,
 11.001049,
 0.568011,
 11.007374,
 0.56833756,
```
