### ISSUE TITLE
How can I get the dataset?

### ISSUE THREAD

**Issue by coolKeen** [gy20073/BDD_Driving_Model#8]
Hi,I have signed up.But it seem that there isn't any email to me?So how can I get the dataset?Thanks a lot~

**Comment by coolKeen** [comment]
My email address is scutcswq@126.com or scutcswq@gmail.com ~

**Comment by gy20073** [comment]
the dataset is available at: 

http://data-bdd.berkeley.edu

**Comment by coolKeen** [comment]
Thank a lot,I have received confirmation email.By the way,how long it will take before I  get the download information?

**Comment by xinxueying** [comment]
hello, author~ I can not download the dataset by clicking on the button "Download Dataset".
What's wrong with my  operation？

**Comment by gy20073** [comment]
You should see a pop up window as below 

![screen shot 2018-04-16 at 10 32 22 am](https://user-images.githubusercontent.com/6026892/38825474-90026d5a-4161-11e8-9ad6-310dd9659e07.png)
